[package]
name = "hexify"
version = "0.1.2"
edition = "2021"
authors = ["Jere Käpyaho <2261936+jerekapyaho@users.noreply.github.com>"]

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
hex = "0.4.3"

[[bin]]
name = "hexify"

[[bin]]
name = "unhexify"
